apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: ACKNOWLEDGE_TIMEOUT
  required: true
- name: RESOLVE_TIMEOUT
  required: true
- name: SERVICE_PREFIX
  required: true
- name: ESCALATION_POLICY
  required: true
- name: ESCALATION_POLICY_SILENT
  required: true
- name: SILENT_ALERT_LEGALENTITY_IDS
  value: '["None"]'
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: pagerduty-operator-catalog
  spec:
    sourceType: grpc
    image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
    displayName: pagerduty-operator Registry
    publisher: SRE

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: pagerduty-operator-og
  spec:
    targetNamespaces:
    - pagerduty-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: pagerduty-operator
  spec:
    channel: ${CHANNEL}
    name: pagerduty-operator
    source: pagerduty-operator-catalog
    sourceNamespace: pagerduty-operator

- apiVersion: pagerduty.openshift.io/v1alpha1
  kind: PagerDutyIntegration
  metadata:
    name: osd
    namespace: pagerduty-operator
  spec:
    acknowledgeTimeout: ${{ACKNOWLEDGE_TIMEOUT}}
    resolveTimeout: ${{RESOLVE_TIMEOUT}}
    escalationPolicy: ${{ESCALATION_POLICY}}
    servicePrefix: ${{SERVICE_PREFIX}}
    pagerdutyApiKeySecretRef:
      name: pagerduty-api-key
      namespace: pagerduty-operator
    clusterDeploymentSelector:
      matchExpressions:
      # only create PD service for managed (OSD) clusters
      - key: api.openshift.com/managed
        operator: In
        values: ["true"]
      # ignore CD w/ "legacy" noalerts label
      - key: api.openshift.com/noalerts
        operator: NotIn
        values: ["true"]
      # ignore CD w/ ext noalerts label
      - key: ext-managed.openshift.io/noalerts
        operator: NotIn
        values: ["true"]
      # ignore CD for specific organizations
      - key: api.openshift.com/legal-entity-id
        operator: NotIn
        values: ${{SILENT_ALERT_LEGALENTITY_IDS}}
      # ignore CD for any "nightly" clusters
      - key: api.openshift.com/channel-group
        operator: NotIn
        values: ["nightly"]
    targetSecretRef:
      name: pd-secret
      namespace: openshift-monitoring
- apiVersion: pagerduty.openshift.io/v1alpha1
  kind: PagerDutyIntegration
  metadata:
    name: osd-silent
    namespace: pagerduty-operator
  spec:
    acknowledgeTimeout: ${{ACKNOWLEDGE_TIMEOUT}}
    resolveTimeout: ${{RESOLVE_TIMEOUT}}
    escalationPolicy: ${{ESCALATION_POLICY_SILENT}}
    servicePrefix: ${SERVICE_PREFIX}_silent
    pagerdutyApiKeySecretRef:
      name: pagerduty-api-key
      namespace: pagerduty-operator
    clusterDeploymentSelector:
      matchExpressions:
      # only create PD service for managed (OSD) clusters
      - key: api.openshift.com/managed
        operator: In
        values: ["true"]
      # ignore CD w/ "legacy" noalerts label
      - key: api.openshift.com/noalerts
        operator: NotIn
        values: ["true"]
      # ignore CD w/ ext noalerts label
      - key: ext-managed.openshift.io/noalerts
        operator: NotIn
        values: ["true"]
      # for the "silent" PDI, create when CD in specific organizations we ignore in the "osd" (regular) PDI
      - key: api.openshift.com/legal-entity-id
        operator: In
        values: ${{SILENT_ALERT_LEGALENTITY_IDS}}
    targetSecretRef:
      name: pd-secret
      namespace: openshift-monitoring

- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    name: pagerduty-integration-api-secret
    namespace: pagerduty-operator
  spec:
    groups:
      - name: pagerduty-integration-api-secret
        rules:
          - alert: PagerDutyIntegrationAPISecretError
            annotations:
              message: PagerDuty Operator is failing to load PAGERDUTY_API_KEY from Secret specified in PagerDutyIntegration {{ $labels.pagerdutyintegration_name }}. Either the Secret might be missing, or the key might be missing from within the Secret.
            expr: pagerdutyintegration_secret_loaded < 1
            for: 15m
            labels:
              severity: warning
